# This is the file generated by the cyberdog_bringup project on the 0c5bba841252 host at time 2026.03.28-10.17.30.
# Copyright (c) 2023 Beijing Xiaomi Mobile Software Co., Ltd. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
import sys
import platform
from launch import LaunchDescription
from launch.actions import LogInfo
from launch.actions import DeclareLaunchArgument
from launch.substitutions import EnvironmentVariable
from launch.substitutions import LaunchConfiguration
from ament_index_python.packages import get_package_share_directory

from mi.cyberdog_bringup.manual import preprocessing
from mi.cyberdog_bringup.manual import get_namespace

preprocessing()

from launch_ros.actions import Node
def generate_launch_description():
    user_env_var = 'USERNAME' if platform.system() == 'Windows' else 'USER'
    return LaunchDescription([
        LogInfo(msg=(EnvironmentVariable(name=user_env_var), ' 正在初始化 base launch ...')),
        Node(
            package='connector',
            executable='connector',
            output='screen',
            namespace=get_namespace(),
        ),
        # Node(
        #     package='cyberdog_audio',
        #     executable='cyberdog_audio',
        #     output='screen',
        #     namespace=get_namespace(),
        # ),
        Node(
            package='device_manager',
            executable='device_manager',
            output='screen',
            namespace=get_namespace(),
        ),
        Node(
            package='sensor_manager',
            executable='sensor_manager',
            output='screen',
            namespace=get_namespace(),
        ),
        Node(
            package='motion_manager',
            executable='motion_manager',
            output='screen',
            namespace=get_namespace(),
        ),
        Node(
            package='realsense2_camera',
            executable='realsense2_actuator_node',
            output='screen',
            namespace=get_namespace(),
        ),
        Node(
            package='cyberdog_manager',
            executable='cyberdog_manager',
            output='screen',
            namespace=get_namespace(),
        ),
        DeclareLaunchArgument(
            name='odom_frame', default_value='odom',
            description='腿式里程计的坐标系名称',
        ),
        DeclareLaunchArgument(
            name='base_frame', default_value='base_link_leg',
            description='腿式里程计的子坐标系名称',
        ),
        DeclareLaunchArgument(
            name='map_frame', default_value='map',
            description='全局坐标系名称，暂时未用到',
        ),
        DeclareLaunchArgument(
            name='tf_pub', default_value='False',
            description='是否发布tf',
        ),
        Node(
            package='motion_bridge',
            executable='odom_out_publisher',
            parameters=[
            {
                'odom_frame': LaunchConfiguration('odom_frame'),
                'base_frame': LaunchConfiguration('base_frame'),
                'map_frame': LaunchConfiguration('map_frame'),
                'tf_pub': LaunchConfiguration('tf_pub'),
            },
            ],
            output='screen',
            namespace=get_namespace(),
        ),
        Node(
            package='motion_bridge',
            executable='motor_bridge',
            output='screen',
            namespace=get_namespace(),
        ),
        # Node(
        #     package='cyberdog_grpc',
        #     executable='app_server',
        #     output='screen',
        #     namespace=get_namespace(),
        # ),
        # Node(
        #     package='bes_transmit',
        #     executable='bes_transmit_waiter',
        #     output='screen',
        #     namespace=get_namespace(),
        # ),
        # Node(
        #     package='cyberdog_vp_engine',
        #     executable='cyberdog_vp_engine',
        #     emulate_tty=True,
        #     output='screen',
        #     namespace=get_namespace(),
        # ),
        # Node(
        #     package='cyberdog_face',
        #     executable='cyberdog_face',
        #     output='screen',
        #     namespace=get_namespace(),
        # ),
        # Node(
        #     package='cyberdog_action',
        #     executable='cyberdog_action',
        #     output='screen',
        #     namespace=get_namespace(),
        # ),
        # Node(
        #     package='cyberdog_interactive',
        #     executable='cyberdog_interactive',
        #     output='screen',
        #     namespace=get_namespace(),
        # ),
        # Node(
        #     package='cyberdog_train',
        #     executable='cyberdog_train',
        #     output='screen',
        #     namespace=get_namespace(),
        # ),
        # Node(
        #     package='cyberdog_ai_sports',
        #     executable='cyberdog_ai_sports',
        #     output='screen',
        #     namespace=get_namespace(),
        # ),
    ])
