/**:
  ros__parameters:
    status_period_sec: 5.0
    namespace: ["cyberdog_1"]
    namespace_index: 0

    # odom_transform_node 输出；节点会自动拼成 /cyberdog_1/odom_global
    input_odom_topic: /odom_global

    # RViz Fixed Frame 建议设为 tag_global；tag_global -> tag_0_observation 由 odom_transform_node 发布
    target_frame_id: tag_global
    output_child_frame_id: base_link
    output_topic_prefix: /viz/tags

    # 可视化只关心最新位姿，跨机 DDS 使用 BestEffort 可以避免 Reliable 重传造成显示滞后。
    subscribe_best_effort: true
    publish_best_effort: true
    publish_tf: true
    tf_publish_every_n: 1

    # tags_visual 自己从 odom 生成轨迹
    path_max_poses: 1000
    path_publish_every_n: 1

    pose_text_enabled: true
    pose_text_topic: /viz/tags/pose_text
    pose_text_z_offset: 0.6
    pose_text_scale: 0.18
    marker_publish_every_n: 5

    robot_marker_enabled: true
    robot_marker_topic: /viz/tags/robot_marker

    # RViz 配置中的 Image 默认订阅 /vins/image1。
    image_enabled: true
    image_input_topic: /camera/infra1/image_rect_raw
    image_output_topic: /vins/image1
